# Generated by Django 3.0.3 on 2020-05-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fathersName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('admissionClass', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=25)),
                ('subject1', models.CharField(max_length=225)),
                ('subject2', models.CharField(max_length=225)),
                ('subject3', models.CharField(max_length=225)),
                ('subject4', models.CharField(max_length=225)),
                ('subject5', models.CharField(max_length=225)),
                ('email', models.CharField(default='NA', max_length=255)),
                ('aadhar', models.CharField(default='NA', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('teacher', models.CharField(max_length=225)),
            ],
        ),
    ]
