# Generated by Django 3.0.3 on 2020-05-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='teacher',
            new_name='paper',
        ),
    ]
