# Generated by Django 3.0.3 on 2020-05-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200517_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.CharField(default='none', max_length=225),
        ),
    ]
